Document: tern
Title: Debian tern Manual
Author: <insert document author here>
Abstract: This manual describes what tern is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tern/tern.sgml.gz

Format: postscript
Files: /usr/share/doc/tern/tern.ps.gz

Format: text
Files: /usr/share/doc/tern/tern.text.gz

Format: HTML
Index: /usr/share/doc/tern/html/index.html
Files: /usr/share/doc/tern/html/*.html
